FROM python:3.11-slim

# Set working directory
WORKDIR /app

COPY requirements-consumer.txt .
COPY BookEventsConsumer.py .
COPY SarahMaasAzureOCR.py .
COPY DecryptCredentials.py .

# Encrypted credential files
COPY encrypted*.txt ./

RUN pip install --no-cache-dir -r requirements-consumer.txt

CMD ["sh", "-c", "python BookEventsConsumer.py"]